//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineEDUschoolManaementSystemMVC.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int ID { get; set; }
        public string courseName { get; set; }
        public decimal coursePrice { get; set; }
        public string introduction { get; set; }
        public string description { get; set; }
        public Nullable<int> numberOfLectures { get; set; }
        public string img { get; set; }
        public int lecturerID { get; set; }
        public int categoryID { get; set; }
        public Nullable<decimal> discountPrice { get; set; }
        public Nullable<int> discount { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Lecturer Lecturer { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
