//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineEDUschoolManaementSystemMVC.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lecturer
    {
        public Lecturer()
        {
            this.Courses = new HashSet<Course>();
        }
    
        public int ID { get; set; }
        public string lecturerName { get; set; }
        public string description { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string img { get; set; }
    
        public virtual ICollection<Course> Courses { get; set; }
    }
}
