//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineEDUschoolManaementSystemMVC.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public OrderDetail()
        {
            this.Carts = new HashSet<Cart>();
        }
    
        public int ID { get; set; }
        public int userID { get; set; }
        public int courseID { get; set; }
        public Nullable<decimal> price { get; set; }
    
        public virtual ICollection<Cart> Carts { get; set; }
        public virtual Course Course { get; set; }
    }
}
