//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineEDUschoolManaementSystemMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseTbl
    {
        public int courseId { get; set; }
        public string courseName { get; set; }
        public decimal coursePrice { get; set; }
        public string introduction { get; set; }
        public string description { get; set; }
        public int numberOfLectures { get; set; }
        public Nullable<int> discount { get; set; }
        public string img { get; set; }
        public int lecturerId { get; set; }
    
        public virtual LecturerTbl LecturerTbl { get; set; }
    }
}
